config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :spaceships do
    resources :bookings, except: :index do
      resources :reviews
    end
  end

  resources :bookings, only: [:index, :destroy]
  get "myspaceships", to: "spaceships#myindex"

  get "bookings", to: "reviews#new"


  get "upcoming", to: "bookings#upcoming"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :spaceship
  has_many :reviews, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :comment, presence: true
  validates :rating, presence: true
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo
  # has_many :reviews, dependent: :destroy
  validates :name, :description, :capacity, :price, :speed, presence: true
  validates :capacity, :price, :speed, numericality: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # before_action :set_spaceship, only: %i[new create]

  def new
    @spaceship = Spaceship.find(params[:spaceship_id])
    @booking = Booking.new
  end

  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def upcoming
    @my_spaceships = Spaceship.where(user_id: current_user.id)
    # @bookings = Booking.all
    # if @bookings.spaceship_id == current_user.spaceship_id
    #   @bookings.save
    # end

    # @bookings = booking.where()
    # find the bookings from the database that contain id of one of spaceships id.
    # now spaceships contain ids in arra
  end

  def create
    @spaceship = Spaceship.find(params[:spaceship_id])
    @booking = Booking.new(booking_params)
    @booking.spaceship = @spaceship
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to booking_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:spaceship_id, :start_date, :end_date)
  end

  # def set_spaceship
  #   @spaceship = Spaceship.find(params[:spaceship_id])
  # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @spaceship = Spaceship.find(params[:spaceship_id])
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @spaceship = Spaceship.find(params[:spaceship_id])
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to bookings_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @spaceships = Spaceship.all
    if params[:query].to_i.positive?
      capacity_query = params[:query].to_i
      @spaceships = Spaceship.where("capacity >= #{capacity_query}")
    elsif params[:query].present?
      @spaceships = Spaceship.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @spaceships = Spaceship.all
    end
  end

  def myindex
    @spaceships = Spaceship.where(user_id: current_user.id)
  end

  def show
    @spaceship = Spaceship.find(params[:id])
  end

  def new
    @spaceship = Spaceship.new(params[:id])
  end

  def create
    @spaceship = Spaceship.new(spaceship_params)
    @spaceship.user = current_user
    if @spaceship.save
      redirect_to spaceship_path(@spaceship)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @spaceship = Spaceship.find(params[:id])
  end

  def update
    @spaceship = Spaceship.find(params[:id])
    @spaceship.update(spaceship_params)
    redirect_to spaceships_path(@spaceship)
  end

  def destroy
    @spaceship = Spaceship.find(params[:id])
    @spaceship.destroy
    redirect_to spaceships_path, status: :see_other
  end

  private

  def spaceship_params
    params.require(:spaceship).permit(:name, :description, :armaments, :capacity, :price, :speed, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>My Bookings</h1>
<br>

<div class="row justify-content-center">
  <% @bookings.each do |booking| %>
          <ol>
          <div class="card m-4">
            <div class="card-header p-3">
                <div class="card-body">
                  <h4><%=booking.spaceship.name%></h4>
                  <% if booking.spaceship.photo.attached? %>
                    <%= cl_image_tag booking.spaceship.photo.key, height: '150', width: '200' %>
                  <% else %>
                    <img src="https://media.sketchfab.com/models/0e97fb0190244216a056909bbd749b9f/thumbnails/77649cbaea4849aeb3c98a70547c39ba/ef0475805a5a4442a15e3b681a0ec389.jpeg", height: '150', width: '200'>
                  <% end %>
                  <p></p>
                  <h6>Start: <%= booking.start_date.strftime("%d/%m/%Y") %></h6>
                  <h6>End: <%= booking.end_date.strftime("%d/%m/%Y") %></h6>
                  <h6>Total price: <%= total = booking.spaceship.price*((booking.end_date - booking.start_date)/86400) %></h6>
                  <%= link_to "Cancel Booking", booking_path(booking), class: "btn", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn" %>
                  <%= link_to "Leave a Review", "", class: "btn" %>
            </div>
            </div>
            </div>
          </ol>
        <% end %>
</div>

app/views/bookings/new.html.erb
<div class="form-container">
  <div class="form-inputs">
    <body>
      <br>
      <br>
      <%= simple_form_for([@spaceship, @booking]) do |f| %>
        <%# <%= f.input :rating %>
        <%# <%= f.input :content %>

        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <%= "Total cost = #{@spaceship.price}"  %>
        <br><br>
        <%=f.submit %>
      <% end %>
    </body>
 </div>
</div>

<%# show total cost, spaceship. %>

app/views/bookings/upcoming.html.erb
<%# iterate spaceship.bookings %>
<h1>Upcoming trips</h1>
<% @my_spaceships.each do |spaceship|%>
  <% spaceship.bookings.each do |booking| %>
    <ol>
      <div class="card m-4">
        <div class="card-header p-3">
          <div class="card-body">
            <h4><%=booking.spaceship.name%></h4>
            <h6>Start: <%= booking.start_date.strftime("%d/%m/%Y") %></h6>
            <h6>End: <%= booking.end_date.strftime("%d/%m/%Y") %></h6>
            <h6>Total price: <%= total = booking.spaceship.price*((booking.end_date - booking.start_date)/86400) %></h6>
            <%= link_to "Cancel Booking", booking_path(booking), class: "btn", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn" %>
          </div>
        </div>
      </div>
    </ol>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AstroPort</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="main-body">
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%# navbar %>

<div class = "info">
  <p></p>
  <p>Whether you've got a ship lying around or looking for one to make a trip, Astroport is here for you.</p>
  <p>AstroPort is a way for fellow space explorers to get together and meet each others exploring needs.</p>
  <p></p>
  <%= button_to "View Fleet", "spaceships", :id => "spaceship-btn", :method => :get %>
</div>

<div class="container">
  <div id ="ship-carousel" class="carousel slide" data-bs-ride="carousel" >
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#ship-carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#ship-carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#ship-carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>

  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="4000">
       <%= image_tag("millennium-falcon.png") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Universal space travel</h5>
        <p>Whatever your budget we can get you from A to BetaGammaV!</p>
      </div>
    </div>

    <div class="carousel-item" data-bs-interval="4000">
      <%= image_tag("RazorCrest.webp") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Intergalactic Raiding</h5>
        <p>Whether you're just going to raid some primitive peoples <br> or conquer galaxies, we have the ship for you!</p>
      </div>
    </div>

    <div class="carousel-item" data-bs-interval="4000">
      <%= image_tag("u-wing.webp")  %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Long or short distance space travel</h5>
        <p>We have spaceships for all durations, whether is just a quick hop <br> across the galaxy or a long trip to explore new galaxies.</p>
      </div>
    </div>
  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#ship-carousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#ship-carousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>

app/views/reviews/index.html.erb
<h1>My Bookings</h1>
<br>


<% @spaceship.reviews.each do |review| %>
    <p><%= review.comment %></p>
    <p><%= review.rating %></p>
    <%# link_to "See Reviews", new_spaceship_booking_review_path(booking.spaceship_id, booking), class: "btn" %>
  <% end %>

app/views/reviews/new.html.erb
<%= simple_form_for([@spaceship, @booking, @review]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>
    <p>2785 AstroPort, Inc.  Privacy. Terms. Sitemap. Galactic Slavery Accord. Company Details.</p>
  </div>
  <div class="icons">
    <h3 class="fa-solid fa-satellite"></h3>
    <h3 class="fa-brands fa-reddit-alien"></h3>
    <h3 class="fa-solid fa-meteor"></h3>
  </div>
</div>





<%# class ="fa-brands fa-reddit-alien" %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag("logo.png") %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="row align-center"><h1> <%= "AstroPort : : ꚣꚤꚥꚦ 𖨔𖨕𖨖𖨗" %> </h1></div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "bender.jpeg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "My Spaceships", myspaceships_path, class: "dropdown-item" %>
              <%= link_to "Add Spaceship", new_spaceship_path, class: "dropdown-item" %>
              <%= link_to "View Fleet", spaceships_path, class: "dropdown-item" %>
              <%= link_to "Upcoming Trips", upcoming_path, class: "dropdown-item"  %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">

            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/spaceships/edit.html.erb
<div class="form-container-spaceship">
  <div class="form-inputs">
    <br>
      <h1>Update your spaceship!</h1>
      <%= simple_form_for [@spaceship] do |f| %>
        <div class="form-bar">
          <%= f.input :name %>
        </div>
        <div class="form-bar">
          <%= f.input :description %>
        </div>
        <div class="form-bar">
          <%= f.input :armaments %>
        </div>
        <div class="form-bar">
          <%= f.input :capacity %>
        </div>
        <div class="form-bar">
          <%= f.input :speed %>
        </div>
        <div class="form-bar">
          <%= f.input :price %>
        </div>
        <div class="form-bar">
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/spaceships/index.html.erb
<div class="containerr">
  <div class="filters justify-content-center">
    <div class="filter"><%= image_tag("mercury.png", height: '40', width: '40') %><p></p>Mercury</div>
    <div class="filter"><%= image_tag("venus.png", height: '40', width: '40') %><p></p>Venus</div>
    <div class="filter"><%= image_tag("mars.png", height: '40', width: '40') %><p></p>Mars</div>
    <div class="filter"><%= image_tag("jupiter.png", height: '40', width: '40') %><p></p>Jupiter</div>
    <div class="filter"><%= image_tag("saturn.png", height: '40', width: '40') %><p></p>Saturn</div>
    <div class="filter"><%= image_tag("uranus.png", height: '40', width: '40') %><p></p>Uranus</div>
    <div class=filter><%= image_tag("neptune.png", height: '40', width: '40') %><p></p>Neptune</div>
  </div>

  <div class="container">
    <div class="searchbar">
      <%= form_with url: spaceships_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Search by name or capacity..."
        %>

        <%= submit_tag "Launch!", class: "btn btn-dark" %>
      <% end %>

    </div>

    </div>
  </div>





  <div class="row justify-content-center">
    <% @spaceships.each do |spaceship| %>
        <%= link_to spaceship_path(spaceship), class:"card col-5" do %>
        <% if spaceship.photo.attached? %>
          <%= cl_image_tag spaceship.photo.key, height: '150', width: '200' %>
        <% else %>
            <img src="https://media.sketchfab.com/models/0e97fb0190244216a056909bbd749b9f/thumbnails/77649cbaea4849aeb3c98a70547c39ba/ef0475805a5a4442a15e3b681a0ec389.jpeg", height: '150', width: '200'>
        <% end %>
        <h5><%= spaceship.name %></h5>
        <h6>Speed: <%= spaceship.speed %></h6>
        <h6>Capacity: <%= spaceship.capacity %></h6>
        <h6>Armament: <%= spaceship.armaments %></h6>
        <h6>Price: ⓩ<%= spaceship.price %></h6>
        <h6>Rating: <%= spaceship.rating %><%= image_tag("gold_star.png", height: '20', width: '20') %></h6>
      <% end %>
    <% end %>
</div>

<!--
      <%= form_with url: spaceships_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Passengers..."
          %>
          <%= submit_tag "Find", class: "btn btn-dark" %>
        <% end %>
-->

app/views/spaceships/myindex.html.erb
<h1>My Spaceships</h1>

  <div class="row justify-content-center">
    <% @spaceships.each do |spaceship| %>
        <%= link_to spaceship_path(spaceship), class:"card col-5" do %>
        <% if spaceship.photo.attached? %>
          <%= cl_image_tag spaceship.photo.key, height: '150', width: '200' %>
        <% else %>
            <img src="https://media.sketchfab.com/models/0e97fb0190244216a056909bbd749b9f/thumbnails/77649cbaea4849aeb3c98a70547c39ba/ef0475805a5a4442a15e3b681a0ec389.jpeg", height: '150', width: '200'>
        <% end %>
        <h5><%= spaceship.name %></h5>
        <h6>Speed: <%= spaceship.speed %></h6>
        <h6>Capacity: <%= spaceship.capacity %></h6>
        <h6>Armament: <%= spaceship.armaments %></h6>
        <h6>Price: ⓩ<%= spaceship.price %></h6>
        <h6>Rating: <%= spaceship.rating %><%= image_tag("gold_star.png", height: '20', width: '20') %></h6>
      <% end %>
    <% end %>
</div>


<%#
<%= link_to "Edit Spaceship", edit_spaceship_path(@spaceship), class: "btn btn-primary" %>

app/views/spaceships/myspaceships.html.erb
<h1>Your Ships:</h1>

app/views/spaceships/new.html.erb
<div class="form-container-spaceship">
  <div class="form=inputs">
    <div class="create">
    <br>
      <h1>Become a Captain! Add your Spaceship below:</h1>

      <%= simple_form_for [@spaceship] do |f| %>
        <div class="form-bar">
            <%= f.input :name %>
          </div>
          <div class="form-bar">
            <%= f.input :description %>
          </div>
          <div class="form-bar">
            <%= f.input :armaments %>
          </div>
          <div class="form-bar">
            <%= f.input :capacity %>
          </div>
          <div class="form-bar">
            <%= f.input :speed %>
          </div>
          <div class="form-bar">
            <%= f.input :price %>
          </div>
          <div class="form-bar">
            <%= f.input :photo, as: :file %>
          </div>
          <%= f.button :submit, class: "btn" %>
        <% end %>
    </div>
  </div>
</div>

app/views/spaceships/show.html.erb
<div class="container">
  <div class="view-page">
    <div class="card-view">
      <h2><%= @spaceship.name %></h2>
      <p></p>
      <p><div class="view-content">Description: <%=@spaceship.description %></p></div>
      <p><div class="view-content">Armament: <%= @spaceship.armaments %></p></div>
      <p><div class="view-content">Speed: <%= @spaceship.speed %> Lightyears/Second</p></div>
      <p><div class="view-content">Price: ⓩ<%= @spaceship.price %> Flugozian Credits.</p></div>
      <p><div class="view-content">Capacity: <%= @spaceship.capacity %> Non-Crew Passengers<p></div>
    </div>
    <% if @spaceship.photo.attached? %>
      <div class="view-img"><%= cl_image_tag @spaceship.photo.key, height: 600, width: 650 %></div>
    <% else %>
      <div class="view-img"><img src="https://media.sketchfab.com/models/0e97fb0190244216a056909bbd749b9f/thumbnails/77649cbaea4849aeb3c98a70547c39ba/ef0475805a5a4442a15e3b681a0ec389.jpeg" alt=""></div>
    <% end %>
  </div>
  <p></p>
    <% if @spaceship.user != current_user %>
      <%= link_to "Make a booking", new_spaceship_booking_path(@spaceship, @booking), class: "btn" %>
      <%= link_to "Reviews!", "", class: "btn" %>
      <%= link_to "Back", spaceships_path, class: "btn"  %>
    <% end %>
    <% if @spaceship.user == current_user %>
      <%= link_to "Edit Details", edit_spaceship_path(@spaceship), class: "btn" %>
      <%= link_to "Remove My Spaceship", spaceship_path(@spaceship), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn" %>

    <% end %>
    <% @spaceship.reviews.each do |review| %>
      <p><%= review.comment %></p>
      <p><%= review.rating %></p>
      <%# <%= link_to "See Reviews", new_spaceship_booking_review_path(booking.spaceship_id, booking), class: "btn" %> %>
    <% end %>


</div>